### PR TITLE
Port some bits to Python 3

### PR DESCRIPTION
**Pull request by rodrigc**
This is a smaller subset of https://github.com/twisted/twistedchecker/pull/113

### CODE REVIEW

**Comment by rodrigc** [comment]
@hawkowl @glyph I took a subset of @hawkowl's patches from https://github.com/twisted/twistedchecker/pull/113 and put it in here.

**Comment by rodrigc** [comment]
@hawkowl @glyph I'd like to merge this if it is OK with you.

**Comment by glyph** [comment]
@rodrigc "0% of diff target hit" seems to be a bit of a problem :-\. Is this just codecov acting up?

**Comment by rodrigc** [comment]
The .travis.yml file is completely botched in this repository.

**Comment by rodrigc** [comment]
@glyph I fixed the tox.ini and .travis.yml file, so the coverage results are now working here.

**Pull request merged**
