### PR TITLE
Comments containing \r \n \t etc shouldn't report an error.

### PR DESCRIPTION
**Pull request by adiroiban**
The following comment shouldn't be considered an error.

# '\r\n' is the default, but we set it just to be explicit in this test.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-07-12T16:26:42Z
 * owner: tom.prince
 * the launchpad url was https://bugs.launchpad.net/bugs/1200695

### CODE REVIEW

**Comment by adiroiban** [comment]
Please take a look at latest patch.

I have no idea why strings were removed from the comments. I have removed that code and tried to come up with other examples.

Thanks!

**Comment by glyph** [comment]
This looks fine to me, but I guess now that I've merged some other things, we need to merge master back in.

**Comment by adiroiban** [comment]
Ok. Merged and resolved conflicts.

**Comment by adiroiban** [comment]
This was waiting review for a long time :(

**Pull request merged**
