### PR TITLE
Do automatic release to PyPi from Travis CI

### PR DESCRIPTION
**Pull request by adiroiban**
As commented by @glyph  in #83 it would be nice to have automatic deployment to PyPi.

Travis CI has support for this http://docs.travis-ci.com/user/deployment/pypi/

More info here about why all_branches is required
http://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A

I have pushed an initial change to travis config file.

I think that is better to create a new PyPi account dedicated for this auto publishing process.

To have this working someone need to create an account on PyPi and send me the encrypted password.

Another option, is to give me permissions to PyPi and GitHub for twistedcheker project, and I can take care of the rest.

Thanks!

### CODE REVIEW

**Comment by adiroiban** [comment]
Any hope for this branch to be reviewed?

Thanks!

**Comment by glyph** [comment]
Adi, it looks like this basically does the right thing, but it would be good to get the actual encrypted secret in there as part of this PR.  Do I need to add you to the twistedchecker release team so you can encrypt something?  Should we create a dedicated release user for travis?

**Comment by adiroiban** [comment]
As a best practice I think that we need a dedicated release user for Travis and encrypt its password.
The account will need a dedicated email address.
The account can have an email address which is forwarded to multiple persons, so that later it can be used the change the password.
For encryption we can use this tool https://rkh.github.io/travis-encrypt/public/index.html.

**Comment by adiroiban** [comment]
Was moved to https://github.com/twisted/twistedchecker/pull/108 and I have removed the original repo

**Pull request closed without merging**
