### PR TITLE
Lift @param/@type requirement for opt_ methods.

### LINKED ISSUE #134: twistedchecker mandates @param on options
Context: https://github.com/twisted/twisted/pull/601#issuecomment-262439865

### PR DESCRIPTION
**Pull request by exarkun**
Fixes #134

### CODE REVIEW

**Comment by markrwilliams** [comment]
Thanks, this was annoying.

**Comment by markrwilliams** [comment]
@adiroiban Could you please push a new release to PyPI?  Thanks!

**Comment by adiroiban** [comment]
done... it is auto-released when a new tag is created https://pypi.python.org/pypi/TwistedChecker

**Comment by adiroiban** [comment]
@markrwilliams you should also be able tp do a release.

The README file contains. 

```

Releasing a new version is done via Travis-CI.
First commit the version update in a master and wait for test to pass.
Create a tag on local branch and then push it::

    git tag 1.2.3
    git push --tags
```

isn't that good enough?
Please suggest how to change the doc to make it clear that anybody who can create a tag, can do a release :)

**Pull request merged**
